# Dockerfile.frontend
FROM node:lts

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
# Changes to these files invalidate this layer, but not the npm install layer if cache is hit
COPY frontend/package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of your frontend application code
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
