    version: '3.9'

    services:
      db:
        image: postgres:14
        container_name: hr_postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          POSTGRES_DB: hr_management_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin@vellore
        ports:
          - "5432:5432"

      backend:
        build:
          context: .
          dockerfile: Dockerfile.backend
        container_name: hr_backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./backend:/app
        ports:
          - "8000:8000"
        depends_on:
          - db
        environment:
          - DEBUG=1
          - DATABASE_NAME=hr_management_db
          - DATABASE_USER=admin
          - DATABASE_PASSWORD=admin@vellore
          - DATABASE_HOST=db
          - DATABASE_PORT=5432

      frontend:
        build:
          context: .
          dockerfile: Dockerfile.frontend
        container_name: hr_frontend
        ports:
          - "5173:5173"
        depends_on:
          - backend
        environment:
          # --- ADD THESE LINES ---
          - VITE_API_BASE_URL=http://13.201.128.13:8000
          # --- END ADDITION ---

    volumes:
      postgres_data:
    
