version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hr_management_db
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin@vellore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: npm start

volumes:
  postgres_data:
