# Generated by Django 5.2.3 on 2025-06-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban_code', models.CharField(blank=True, max_length=34, null=True)),
                ('commission_type', models.CharField(blank=True, choices=[('km', 'KM Based'), ('order', 'Order Based'), ('fixed', 'Fixed Commission')], max_length=10, null=True)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if KM Based', max_digits=10, null=True)),
                ('min_km', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if KM Based', max_digits=10, null=True)),
                ('rate_per_order', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if Order Based', max_digits=10, null=True)),
                ('fixed_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if Fixed Commission', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
