# Generated by Django 5.2.3 on 2025-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='commission_percentage',
        ),
        migrations.AddField(
            model_name='company',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('km', 'KM Based'), ('order', 'Order Based'), ('fixed', 'Fixed Commission')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fixed_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if Fixed Commission', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='iban_code',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='min_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if KM Based', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if KM Based', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rate_per_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable only if Order Based', max_digits=10, null=True),
        ),
    ]
