# attendance/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    AttendanceViewSet,
    CheckinLocationViewSet,
    ApartmentLocationViewSet,
    MonthlyAttendanceSummaryViewSet,
    TerminationViewSet,
    WarningLetterViewSet,
    CompanyViewSet, # Make sure CompanyViewSet is imported if used in router
    VehicleRegistrationViewSet # Make sure VehicleRegistrationViewSet is imported if used in router
)

router = DefaultRouter()
router.register(r'attendance', AttendanceViewSet, basename='attendance')
router.register(r'checkin-locations', CheckinLocationViewSet, basename='checkin-location')
router.register(r'apartment-locations', ApartmentLocationViewSet, basename='apartment-location')
router.register(r'monthly-summary', MonthlyAttendanceSummaryViewSet) # Register the monthly summary endpoint
router.register(r'warning-letters', WarningLetterViewSet, basename='warning-letters') # Changed basename for consistency
router.register(r'terminations', TerminationViewSet)
router.register(r'companies', CompanyViewSet) # Assuming these are used
router.register(r'vehicle-registrations', VehicleRegistrationViewSet) # Assuming these are used


urlpatterns = [
    # This line includes ALL URLs generated by the DefaultRouter,
    # which includes /attendance/current-day/<driver_id>/
    path('', include(router.urls)),
    path('attendance/current-day/<int:driver_id>/', AttendanceViewSet.as_view({'get': 'retrieve_current_day_attendance'}), name='current_day_attendance'),

    # REMOVED the redundant line:
    # path('attendance/current-day/<int:driver_id>/', AttendanceViewSet.as_view({'get': 'retrieve_current_day_attendance'}), name='current_day_attendance'),
]
