# Generated by Django 5.2.3 on 2025-06-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Admin or HR remarks for approval, rejection, or additional notes')),
                ('driver_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('iqama', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('iqama_document', models.FileField(blank=True, null=True, upload_to='drivers/iqama/')),
                ('iqama_expiry', models.DateField(blank=True, null=True)),
                ('passport_document', models.FileField(blank=True, null=True, upload_to='drivers/passport/')),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='drivers/license/')),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('visa_document', models.FileField(blank=True, null=True, upload_to='drivers/visa/')),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='drivers/medical/')),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('insurance_paid_by', models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's insurance?", max_length=10, null=True)),
                ('accommodation_paid_by', models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's accommodation rent?", max_length=10, null=True)),
                ('phone_bill_paid_by', models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's phone bill?", max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='company.company')),
            ],
        ),
    ]
