# Generated by Django 5.2.3 on 2025-06-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('drivers', '0004_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='company.company'),
        ),
    ]
