# Generated by Django 5.2.3 on 2025-06-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_vehicle'),
        ('vehicle', '0004_vehiclelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vehicle.vehicleregistration'),
        ),
    ]
