# Generated by Django 5.2.3 on 2025-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driverId',
            field=models.IntegerField(default='1'),
        ),
    ]
