# Generated by Django 5.2.3 on 2025-06-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_commission_percentage_and_more'),
        ('drivers', '0009_driver_password'),
        ('vehicle', '0004_vehiclelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driverId',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicleregistration'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='company.company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='iqama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='iqama_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/iqama/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='iqama_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/license/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/medical/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/passport/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/visa/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='visa_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
