# Generated by Django 5.2.3 on 2025-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_rename_submitted_at_driver_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accommodation_paid_by',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's accommodation rent?", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_paid_by',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's insurance?", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_bill_paid_by',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('company', 'Company')], help_text="Who pays for the driver's phone bill?", max_length=10, null=True),
        ),
    ]
