# Generated by Django 5.2.3 on 2025-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_driver_accommodation_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='remarks',
            field=models.TextField(blank=True, help_text='Admin or HR remarks for approval, rejection, or additional notes'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
