# Generated by Django 5.2.4 on 2025-07-06 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing assignment', null=True)),
                ('working_days', models.JSONField(default=list, help_text="List of working days: ['monday', 'tuesday', ...]")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Shift Assignment',
                'verbose_name_plural': 'Driver Shift Assignments',
                'ordering': ['-start_date', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('allocated_days', models.IntegerField(default=0, help_text='Days allocated for this year')),
                ('used_days', models.IntegerField(default=0, help_text='Days already used')),
                ('pending_days', models.IntegerField(default=0, help_text='Days in pending requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year', 'driver__driver_name', 'leave_type__name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(help_text='Total number of leave days')),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Comments from admin/HR', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-applied_date', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_days_per_year', models.IntegerField(default=30, help_text='Maximum days allowed per year')),
                ('is_paid', models.BooleanField(default=True, help_text='Is this a paid leave?')),
                ('requires_approval', models.BooleanField(default=True, help_text='Does this leave require approval?')),
                ('advance_notice_days', models.IntegerField(default=1, help_text='Minimum advance notice required in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_deductions_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attendance_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Monthly Attendance Summary',
                'verbose_name_plural': 'Monthly Attendance Summaries',
                'ordering': ['-year', '-month', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible Shift'), ('custom', 'Custom Shift')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration_minutes', models.IntegerField(default=30, help_text='Break duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift Type',
                'verbose_name_plural': 'Shift Types',
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('performance_issues', 'Performance Issues'), ('voluntary_resignation', 'Voluntary Resignation'), ('policy_violation', 'Policy Violation'), ('contract_expiration', 'Contract Expiration'), ('redundancy', 'Redundancy'), ('other', 'Other')], max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='drivers/terminations/')),
                ('generated_letter', models.FileField(blank=True, null=True, upload_to='termination_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termination',
                'verbose_name_plural': 'Terminations',
            },
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('speeding', 'Speeding'), ('reckless_driving', 'Reckless Driving'), ('unauthorized_route', 'Unauthorized Route'), ('vehicle_damage', 'Vehicle Damage'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='drivers/warning_letters/')),
                ('generated_letter', models.FileField(blank=True, null=True, upload_to='warning_letters_generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warning Letter',
                'verbose_name_plural': 'Warning Letters',
            },
        ),
        migrations.CreateModel(
            name='ApartmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('alarm_radius_meters', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_locations', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_locations', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('assigned_time', models.TimeField(blank=True, null=True)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('login_photo', models.ImageField(blank=True, null=True, upload_to='login_photos/')),
                ('login_latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('login_longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('logout_photo', models.ImageField(blank=True, null=True, upload_to='logout_photos/')),
                ('logout_latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('logout_longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('absent', 'Absent'), ('leave', 'Leave')], default='pending', max_length=20)),
                ('reason_for_deduction', models.TextField(blank=True, null=True)),
                ('deduct_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='drivers.driver')),
                ('checked_in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.checkinlocation')),
            ],
            options={
                'ordering': ['-date', 'driver__driver_name'],
            },
        ),
    ]
