# Generated by Django 5.2.3 on 2025-06-20 02:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('speeding', 'Speeding'), ('reckless_driving', 'Reckless Driving'), ('unauthorized_route', 'Unauthorized Route'), ('vehicle_damage', 'Vehicle Damage'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='drivers/warning_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warning Letter',
                'verbose_name_plural': 'Warning Letters',
                'ordering': ['-issued_date', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('alarm_radius_meters', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_locations', to='company.company')),
            ],
            options={
                'verbose_name': 'Apartment/Alarm Location',
                'verbose_name_plural': 'Apartment/Alarm Locations',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_locations', to='company.company')),
            ],
            options={
                'verbose_name': 'Check-in Location',
                'verbose_name_plural': 'Check-in Locations',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_time', models.TimeField(blank=True, null=True)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('login_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/login/')),
                ('login_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('login_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('logout_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/logout/')),
                ('logout_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logout_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On-time'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('reason_for_deduction', models.CharField(blank=True, choices=[('traffic', 'Traffic'), ('personal', 'Personal'), ('logistics_issue', 'Logistics Issue'), ('other', 'Other')], max_length=50, null=True)),
                ('deduct_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='drivers.driver')),
                ('checked_in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_checkins', to='hr.checkinlocation')),
            ],
            options={
                'ordering': ['-date', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_deductions_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attendance_score', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Monthly Attendance Summary',
                'verbose_name_plural': 'Monthly Attendance Summaries',
                'ordering': ['-year', '-month', 'driver__driver_name'],
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('performance_issues', 'Performance Issues'), ('voluntary_resignation', 'Voluntary Resignation'), ('policy_violation', 'Policy Violation'), ('contract_expiration', 'Contract Expiration'), ('redundancy', 'Redundancy'), ('other', 'Other')], max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='drivers/terminations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination_record', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Termination',
                'verbose_name_plural': 'Terminations',
                'ordering': ['-termination_date', 'driver__driver_name'],
            },
        ),
    ]
