# Generated by Django 5.2.3 on 2025-06-19 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_commission_percentage_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlocation',
            name='alarm_radius_meters',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_locations', to='company.company'),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checked_in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_checkins', to='hr.checkinlocation'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='login_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='login_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='login_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/login/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/logout/'),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_locations', to='company.company'),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinlocation',
            name='radius_meters',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='monthlyattendancesummary',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyattendancesummary',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='termination',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termination',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/terminations/'),
        ),
        migrations.AlterField(
            model_name='warningletter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warningletter',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/warning_letters/'),
        ),
    ]
