# Generated by Django 5.2.3 on 2025-06-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_apartmentlocation_alarm_radius_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentlocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='checkinlocation',
            name='is_active',
        ),
    ]
