# Generated by Django 5.2.3 on 2025-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_apartmentlocation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkinlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
