# Generated by Django 5.2.3 on 2025-06-14 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/images/')),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicles/insurance_docs/')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('rc_book_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='vehicles/rc_docs/')),
                ('is_leased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
