# Generated by Django 5.2.3 on 2025-06-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/images/')),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicles/insurance_docs/')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('Chassis_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('rc_book_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='vehicles/rc_docs/')),
                ('is_leased', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleregistration')),
            ],
        ),
    ]
