# Generated by Django 5.2.3 on 2025-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicleregistration_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='Chassis_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
